### ISSUE TITLE
Did not work out of the box

### ISSUE THREAD

**Issue by adarshrao** [thelittlewonder/fbchatviz#1]
Not sure if it's just me but it didn't work right out of the box for me. 

Had to install psutil, then orca and then matplotlib.

And after that, even though it was generating the plots, there was some issue with the word-cloud generation. Kept saying "ValueError: We need at least 1 word to plot a word cloud, got 0."

Just FYI. 

The plots were cool though! Thanks for making this!

**Comment by adarshrao** [comment]
After 20 minutes of trying to run lots of messages 

1. Some of my .json files have a null value in sender_name. The code doesn't run for the null value. 
2. It does not work for group conversations. Found out after I accidentally tried to run it on one.

**Comment by thelittlewonder** [comment]
Fixed! Thanks for pointing out :)

**Comment by chintito4ever** [comment]
$ python plot.py message_1.json
Traceback (most recent call last):
  File "plot.py", line 9, in <module>
    from wordcloud import WordCloud
ModuleNotFoundError: No module named 'wordcloud'

How do I fix this?

**Comment by thelittlewonder** [comment]
Please run `pip install -r requirements.txt` in the project directory before running plot.py
